services:
  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: